# Generated by Django 5.0.7 on 2024-08-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('producer_name', models.CharField(max_length=100)),
                ('offered_quantity', models.PositiveIntegerField()),
                ('unit_price_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_timeline', models.CharField(max_length=100)),
                ('additional_terms_and_conditions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In-progress', 'In-progress'), ('Completed', 'Completed'), ('Declined', 'Declined')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Furniture', 'Furniture'), ('Toys', 'Toys'), ('Groceries', 'Groceries'), ('Other', 'Other')], max_length=50)),
                ('available_quantity', models.PositiveIntegerField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
    ]
