# Generated by Django 5.0.7 on 2024-08-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='additional_terms_and_conditions',
            new_name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.AlterField(
            model_name='offer',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.request'),
        ),
    ]
