# Generated by Django 5.0.7 on 2024-08-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_additional_terms_and_conditions_offer_additional_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offered_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='unit_price_offered',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('In-progress', 'In-progress'), ('Completed', 'Completed'), ('Declined', 'Declined')], default='In-progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Offer send', 'Offer send')], default='Pending', max_length=20),
        ),
    ]
