# Generated by Django 5.0.7 on 2024-08-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_offered_quantity_offer_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In-progress', 'In-progress')], default='Pending', max_length=20),
        ),
    ]
