# Generated by Django 5.0.7 on 2024-08-09 12:28

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('invoice_file', models.FileField(upload_to='invoices/')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.offer')),
            ],
        ),
    ]
