# Generated by Django 5.0.7 on 2024-08-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created']},
        ),
    ]
